package mediation.helper.config;

public enum PLACEHOLDER {
    MAIN_ACTIVITY,
    SUBSCRIPTION_ACTIVITY,
    PRIVACY_ACTIVITY,
    DOWNLOAD_ACTIVITY,
    VIEW_ACTIVITY,
    DATA_ACTIVITY,
    HELP_ACTIVITY,
    ABOUT_ACTIVITY,
    EXIT_ACTIVITY,
    ACTIVITY_1,
    ACTIVITY_2,
    ACTIVITY_3,
    ACTIVITY_4,
    ACTIVITY_5,
    ACTIVITY_6,
    ACTIVITY_7,
    ACTIVITY_8,
    SPLASH_ACTIVITY,
    DEFAULT

}
